ALTER TYPE "ProductDetailAssetType" ADD VALUE IF NOT EXISTS 'MODEL_DISPLAY';
ALTER TYPE "ProductDetailAssetType" ADD VALUE IF NOT EXISTS 'DETAIL_GALLERY';
ALTER TYPE "ProductDetailAssetType" ADD VALUE IF NOT EXISTS 'DELIVERY_GUIDE';
